// Generated types from Supabase schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      segments: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          emoji: string | null;
          routing_rules: Json;
          channel_primary: string | null;
          channel_secondary: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          emoji?: string | null;
          routing_rules?: Json;
          channel_primary?: string | null;
          channel_secondary?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          emoji?: string | null;
          routing_rules?: Json;
          channel_primary?: string | null;
          channel_secondary?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      investor_statuses: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          signals: string[] | null;
          touchpoint_frequency_days: number | null;
          priority_level: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          signals?: string[] | null;
          touchpoint_frequency_days?: number | null;
          priority_level?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          signals?: string[] | null;
          touchpoint_frequency_days?: number | null;
          priority_level?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      prompts: {
        Row: {
          id: string;
          prompt_id: string;
          version: number;
          system: string;
          category: string | null;
          name: string;
          description: string | null;
          content: string;
          variables: string[] | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          prompt_id: string;
          version?: number;
          system: string;
          category?: string | null;
          name: string;
          description?: string | null;
          content: string;
          variables?: string[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          prompt_id?: string;
          version?: number;
          system?: string;
          category?: string | null;
          name?: string;
          description?: string | null;
          content?: string;
          variables?: string[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contents: {
        Row: {
          id: string;
          source_url: string | null;
          source_type: string | null;
          slack_channel_id: string | null;
          slack_message_ts: string | null;
          slack_reactions: Json;
          title: string | null;
          description: string | null;
          duration_seconds: number | null;
          transcript_raw: string | null;
          transcript_structured: Json | null;
          hooks: Json;
          clips: Json;
          audiences: string[];
          content_type: string | null;
          is_evergreen: boolean;
          score: number;
          priority: string;
          is_featured: boolean;
          status: string;
          processing_started_at: string | null;
          processing_completed_at: string | null;
          processing_error: string | null;
          ai_metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source_url?: string | null;
          source_type?: string | null;
          slack_channel_id?: string | null;
          slack_message_ts?: string | null;
          slack_reactions?: Json;
          title?: string | null;
          description?: string | null;
          duration_seconds?: number | null;
          transcript_raw?: string | null;
          transcript_structured?: Json | null;
          hooks?: Json;
          clips?: Json;
          audiences?: string[];
          content_type?: string | null;
          is_evergreen?: boolean;
          score?: number;
          priority?: string;
          is_featured?: boolean;
          status?: string;
          processing_started_at?: string | null;
          processing_completed_at?: string | null;
          processing_error?: string | null;
          ai_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source_url?: string | null;
          source_type?: string | null;
          slack_channel_id?: string | null;
          slack_message_ts?: string | null;
          slack_reactions?: Json;
          title?: string | null;
          description?: string | null;
          duration_seconds?: number | null;
          transcript_raw?: string | null;
          transcript_structured?: Json | null;
          hooks?: Json;
          clips?: Json;
          audiences?: string[];
          content_type?: string | null;
          is_evergreen?: boolean;
          score?: number;
          priority?: string;
          is_featured?: boolean;
          status?: string;
          processing_started_at?: string | null;
          processing_completed_at?: string | null;
          processing_error?: string | null;
          ai_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      hooks: {
        Row: {
          id: string;
          content_id: string | null;
          text: string;
          timestamp: string | null;
          hook_type: string | null;
          used_count: number;
          last_used_at: string | null;
          engagement_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          content_id?: string | null;
          text: string;
          timestamp?: string | null;
          hook_type?: string | null;
          used_count?: number;
          last_used_at?: string | null;
          engagement_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          content_id?: string | null;
          text?: string;
          timestamp?: string | null;
          hook_type?: string | null;
          used_count?: number;
          last_used_at?: string | null;
          engagement_score?: number | null;
          created_at?: string;
        };
      };
      contacts_sync: {
        Row: {
          id: string;
          ghl_id: string;
          ghl_location_id: string | null;
          email: string | null;
          phone: string | null;
          first_name: string | null;
          last_name: string | null;
          segment: string | null;
          investor_status: string | null;
          score: number;
          tags: string[];
          last_touchpoint_at: string | null;
          last_response_at: string | null;
          touchpoint_count: number;
          response_count: number;
          latest_notes: string | null;
          parsed_notes: Json | null;
          last_synced_at: string;
          sync_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ghl_id: string;
          ghl_location_id?: string | null;
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          segment?: string | null;
          investor_status?: string | null;
          score?: number;
          tags?: string[];
          last_touchpoint_at?: string | null;
          last_response_at?: string | null;
          touchpoint_count?: number;
          response_count?: number;
          latest_notes?: string | null;
          parsed_notes?: Json | null;
          last_synced_at?: string;
          sync_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ghl_id?: string;
          ghl_location_id?: string | null;
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          segment?: string | null;
          investor_status?: string | null;
          score?: number;
          tags?: string[];
          last_touchpoint_at?: string | null;
          last_response_at?: string | null;
          touchpoint_count?: number;
          response_count?: number;
          latest_notes?: string | null;
          parsed_notes?: Json | null;
          last_synced_at?: string;
          sync_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      distributions: {
        Row: {
          id: string;
          content_id: string | null;
          contact_sync_id: string | null;
          ghl_contact_id: string | null;
          channel: string;
          message_type: string | null;
          subject: string | null;
          message_content: string | null;
          media_url: string | null;
          external_id: string | null;
          external_url: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          response_received: boolean;
          response_text: string | null;
          response_at: string | null;
          response_sentiment: string | null;
          status: string;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          content_id?: string | null;
          contact_sync_id?: string | null;
          ghl_contact_id?: string | null;
          channel: string;
          message_type?: string | null;
          subject?: string | null;
          message_content?: string | null;
          media_url?: string | null;
          external_id?: string | null;
          external_url?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          response_received?: boolean;
          response_text?: string | null;
          response_at?: string | null;
          response_sentiment?: string | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          content_id?: string | null;
          contact_sync_id?: string | null;
          ghl_contact_id?: string | null;
          channel?: string;
          message_type?: string | null;
          subject?: string | null;
          message_content?: string | null;
          media_url?: string | null;
          external_id?: string | null;
          external_url?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          response_received?: boolean;
          response_text?: string | null;
          response_at?: string | null;
          response_sentiment?: string | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      touchpoint_queue: {
        Row: {
          id: string;
          contact_sync_id: string | null;
          ghl_contact_id: string;
          scheduled_for: string;
          channel: string;
          message_type: string;
          message_content: string | null;
          template_id: string | null;
          status: string;
          processed_at: string | null;
          error_message: string | null;
          distribution_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          contact_sync_id?: string | null;
          ghl_contact_id: string;
          scheduled_for: string;
          channel: string;
          message_type?: string;
          message_content?: string | null;
          template_id?: string | null;
          status?: string;
          processed_at?: string | null;
          error_message?: string | null;
          distribution_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          contact_sync_id?: string | null;
          ghl_contact_id?: string;
          scheduled_for?: string;
          channel?: string;
          message_type?: string;
          message_content?: string | null;
          template_id?: string | null;
          status?: string;
          processed_at?: string | null;
          error_message?: string | null;
          distribution_id?: string | null;
          created_at?: string;
        };
      };
      analytics_events: {
        Row: {
          id: string;
          event_type: string;
          event_category: string | null;
          workflow_name: string | null;
          content_id: string | null;
          contact_id: string | null;
          distribution_id: string | null;
          event_data: Json;
          duration_ms: number | null;
          success: boolean;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          event_category?: string | null;
          workflow_name?: string | null;
          content_id?: string | null;
          contact_id?: string | null;
          distribution_id?: string | null;
          event_data?: Json;
          duration_ms?: number | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          event_category?: string | null;
          workflow_name?: string | null;
          content_id?: string | null;
          contact_id?: string | null;
          distribution_id?: string | null;
          event_data?: Json;
          duration_ms?: number | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
      };
      workflow_logs: {
        Row: {
          id: string;
          workflow_id: string;
          workflow_name: string | null;
          execution_id: string | null;
          status: string | null;
          started_at: string | null;
          completed_at: string | null;
          input_data: Json | null;
          output_data: Json | null;
          error_data: Json | null;
          nodes_executed: number | null;
          duration_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workflow_id: string;
          workflow_name?: string | null;
          execution_id?: string | null;
          status?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          input_data?: Json | null;
          output_data?: Json | null;
          error_data?: Json | null;
          nodes_executed?: number | null;
          duration_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workflow_id?: string;
          workflow_name?: string | null;
          execution_id?: string | null;
          status?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          input_data?: Json | null;
          output_data?: Json | null;
          error_data?: Json | null;
          nodes_executed?: number | null;
          duration_ms?: number | null;
          created_at?: string;
        };
      };
      templates: {
        Row: {
          id: string;
          template_id: string;
          category: string;
          segment: string | null;
          investor_status: string | null;
          name: string;
          description: string | null;
          subject: string | null;
          body: string;
          variables: string[] | null;
          used_count: number;
          last_used_at: string | null;
          open_rate: number | null;
          click_rate: number | null;
          response_rate: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          category: string;
          segment?: string | null;
          investor_status?: string | null;
          name: string;
          description?: string | null;
          subject?: string | null;
          body: string;
          variables?: string[] | null;
          used_count?: number;
          last_used_at?: string | null;
          open_rate?: number | null;
          click_rate?: number | null;
          response_rate?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          category?: string;
          segment?: string | null;
          investor_status?: string | null;
          name?: string;
          description?: string | null;
          subject?: string | null;
          body?: string;
          variables?: string[] | null;
          used_count?: number;
          last_used_at?: string | null;
          open_rate?: number | null;
          click_rate?: number | null;
          response_rate?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      v_content_ready: {
        Row: {
          id: string;
          source_url: string | null;
          source_type: string | null;
          title: string | null;
          description: string | null;
          audiences: string[];
          score: number;
          priority: string;
          status: string;
          created_at: string;
          audience_count: number | null;
          hook_count: number | null;
        };
      };
      v_contact_overview: {
        Row: {
          id: string;
          ghl_id: string;
          email: string | null;
          phone: string | null;
          first_name: string | null;
          last_name: string | null;
          segment: string | null;
          segment_name: string | null;
          investor_status: string | null;
          status_name: string | null;
          score: number;
          last_touchpoint_at: string | null;
          touchpoint_count: number;
          response_count: number;
          touchpoint_frequency_days: number | null;
          total_distributions: number | null;
          total_responses: number | null;
        };
      };
      v_distribution_performance: {
        Row: {
          channel: string;
          message_type: string | null;
          total_sent: number | null;
          opened: number | null;
          clicked: number | null;
          responded: number | null;
          open_rate: number | null;
          click_rate: number | null;
          response_rate: number | null;
        };
      };
    };
    Functions: {};
    Enums: {};
  };
}
